import = ["/home/andrea/.config/alacritty/colors.toml", "/home/andrea/.config/alacritty/fonts.toml"]
live_config_reload = true

[cursor]
unfocused_hollow = false

[cursor.style]
blinking = "On"
shape = "Beam"

[env]
TERM = "alacritty"
WINIT_X11_SCALE_FACTOR = "1.0"

[window]
decorations = "none"
dynamic_title = true
opacity = 0.9
startup_mode = "Windowed"

[scrolling]
history = 10000
multiplier = 3

[window.dimensions]
columns = 82
lines = 24

[window.padding]
x = 19
y = 19

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[hints.enabled]]
binding = { key = "U", mods = "Control|Shift" }
command = "xdg-open"
post_processing = true
hyperlinks = true
mouse.enabled = true
mouse.mods = "Control"
persist = false
regex = "(idea://|file-line://|ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩‘]+"


