# Get editor completions based on the config schema 
"$schema" = 'https://starship.rs/config-schema.json'
 
# Inserts a blank line between shell prompts 
#add_newline = true
 
[directory]
truncation_length = 3
truncate_to_repo = false

# Replace the '❯' symbol in the prompt with '➜' 
[character] # The name of the module we are configuring is 'character' 
success_symbol = '[➜](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'
error_symbol = '[➜](bold red)'

# Disable the package module, hiding it from the prompt completely 
[package] 
format = 'via [ $version](208 bold) '
 
[azure]
disabled = false
format = 'on [$symbol($username)]($style) '
symbol = 'ﴃ '
style = 'blue bold'
 
[helm]
format = 'via [⎈ $version](bold white) '
 
[lua]
format = 'via [ $version](bold blue) '
 
[kubernetes]
format = 'on [󱃾 ($cluster in )$context \($namespace\)](dimmed green) '
disabled = false
 
[golang]
format = 'via [ $version](bold cyan) '
 
[ruby]
#format = ' $version '
format = 'via [ ($version )]($style)'
